// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLUbVdS6VEOi0bpbJjXd5wEUS1r1NuL9I',
    appId: '1:525482222879:web:cf67889378c425dfa33c2a',
    messagingSenderId: '525482222879',
    projectId: 'sam-nft-e4e59',
    authDomain: 'sam-nft-e4e59.firebaseapp.com',
    storageBucket: 'sam-nft-e4e59.firebasestorage.app',
    measurementId: 'G-BEYM8W0KFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhz3bwHwCCb0bgeNqeAtajrXCeKTJB1qA',
    appId: '1:525482222879:android:0367616c68f83c3fa33c2a',
    messagingSenderId: '525482222879',
    projectId: 'sam-nft-e4e59',
    storageBucket: 'sam-nft-e4e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG_gpejdSeEI0qgPK4wrp11RAvEYLA1x4',
    appId: '1:525482222879:ios:fbe15086349561f2a33c2a',
    messagingSenderId: '525482222879',
    projectId: 'sam-nft-e4e59',
    storageBucket: 'sam-nft-e4e59.firebasestorage.app',
    iosBundleId: 'com.example.csamMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG_gpejdSeEI0qgPK4wrp11RAvEYLA1x4',
    appId: '1:525482222879:ios:fbe15086349561f2a33c2a',
    messagingSenderId: '525482222879',
    projectId: 'sam-nft-e4e59',
    storageBucket: 'sam-nft-e4e59.firebasestorage.app',
    iosBundleId: 'com.example.csamMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLUbVdS6VEOi0bpbJjXd5wEUS1r1NuL9I',
    appId: '1:525482222879:web:d925d13e60a7a870a33c2a',
    messagingSenderId: '525482222879',
    projectId: 'sam-nft-e4e59',
    authDomain: 'sam-nft-e4e59.firebaseapp.com',
    storageBucket: 'sam-nft-e4e59.firebasestorage.app',
    measurementId: 'G-B6LJYZ2FGM',
  );

}